### ISSUE TITLE
Flipped rear mirror when used with WFP

### ISSUE THREAD

**Issue by vjadid** [AeroWidescreen/NFSMWHDReflections#5]
The rear view is flipped left/right when this asi is used with thirteenag's WFP/
Tested with latest stable version of both asi.

My install = vanilla black edition 1.3 mw + HQ vinyls + below mods
![asi used](https://user-images.githubusercontent.com/29530546/65375803-102cad00-dcb7-11e9-9a93-982a062c726f.PNG)

Using just HDReflections (ok)
![HD reflections](https://user-images.githubusercontent.com/29530546/65375815-2470aa00-dcb7-11e9-9334-385a63f9fce9.png)

Using HDReflections and WidescreenFixesPack (not ok)
![WFP and HD reflections](https://user-images.githubusercontent.com/29530546/65375848-49651d00-dcb7-11e9-978c-45c15de79bc4.png)

**Comment by AeroWidescreen** [comment]
That doesn't make any sense to me. Paste both of your ini files here, and try disabling MirrorTint.

My tests with the latest stable build and developer build of the widescreen fix produced the same results. I also installed MWFixes in case that was causing any issues. Everything is working fine.

![Mirror](https://i.imgur.com/Hu8z0hm.png)

**Comment by vjadid** [comment]
Okay I'm unable to reproduce the issue now (and I'm pretty unsure why/when this happens as this occasionally occurred in past ).

Below are both ini files
![Capture](https://user-images.githubusercontent.com/29530546/65384697-ede07100-dd42-11e9-8fae-b4e46b2f3b73.PNG)

Will try to find more when this happens again.

**Comment by vjadid** [comment]
Closing, will reopen when I'm able to reproduce issue consistently.

**Comment by vjadid** [comment]
okay this happened again when I updated from 1.2.5 to 1.3.0.
I'm using these ASIs `WFP, HDReflections, XboxRainDroplets`

- Restarted the game and OS, did not fix.
- Reinstalled the game, did not fix.
- Switched to older release then back to latest release, fixed the issue.

Not an issue I guess, just game being weird.

**Comment by AeroWidescreen** [comment]
I've been playing Most Wanted since Friday and I didn't have any problems. That doesn't mean it's not a real issue, but it's hard to fix a problem I can't reproduce or never experienced.

The widescreen fix is responsible for flipping the mirror mask. It does this with `RearviewMirrorFix`. It's possible that the `MirrorTint` feature of HD Reflections is interfering with the byte patterns the widescreen fix relies on, since the code is very close to each other. But a problem like that usually causes the game to crash on launch.

The most I can do is try to move my MirrorTint code further away, and then you could tell me if worked or not. I'll have something for you to test later.

**Comment by vjadid** [comment]
Well the issue is not happening now as it got fixed after switching releases, and I'm not sure if it'll happen again.

**Comment by AeroWidescreen** [comment]
For the record, I determined this problem was likely caused by the widescreen fix. It was flipping the mirror when it needed to to be flipped. I've corrected this in the latest update available on ThirteenAG's website.

**Comment by AeroWidescreen** [comment]
For the record, I determined this problem was likely caused by the widescreen fix. It was flipping the mirror when it didn't need to be be flipped. I've corrected this in the latest update available on ThirteenAG's website.

**Comment by vjadid** [comment]
Thank you!
